# Generated by Django 6.1.1 on 2026-09-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name_kg',
            new_name='category_name_ky',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description_kg',
            new_name='product_description_ky',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name_kg',
            new_name='product_name_ky',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='SubCategory_name_kg',
            new_name='SubCategory_name_ky',
        ),
    ]
