# Generated by Django 6.1.1 on 2026-09-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0002_rename_category_name_kg_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_pl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_pl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_pl',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='SubCategory_name_es',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='SubCategory_name_ky',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='SubCategory_name_pl',
        ),
        migrations.AlterField(
            model_name='product',
            name='SubCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='ozon_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='ozon_app.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='ozon_app.product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sub', to='ozon_app.category'),
        ),
    ]
