# Generated by Django 6.1.1 on 2026-09-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0004_cart_cartitem_favorite_favoriteitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
